#!/bin/sh

# Author: Franklin Webber, 2013
# Based on http://www.novell.com/coolsolutions/feature/15380.html

### BEGIN INIT INFO
# Provides:          bluepill
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: bluepill daemon, providing process monitoring
# Description:       bluepill is a monitoring tool. More info at http://github.com/arya/bluepill.
### END INIT INFO

export PATH="/usr/local/bin:$PATH"

# Check for missing binaries

BLUEPILL_BIN=/usr/local/bin/bluepill

test -x $BLUEPILL_BIN || { echo "$BLUEPILL_BIN not installed";
        if [ "$1" = "stop" ]; then exit 0;
        else exit 5; fi; }

# Check for existence of needed config file and read it

BLUEPILL_CONFIG=/sites/today/blue.pill
test -r $BLUEPILL_CONFIG || { echo "$BLUEPILL_CONFIG not existing";
        if [ "$1" = "stop" ]; then exit 0;
        else exit 6; fi; }

case "$1" in
  start)
    echo -n "Starting bluepill "
    # echo -n "\n$BLUEPILL_BIN load $BLUEPILL_CONFIG\n"
    echo `$BLUEPILL_BIN load $BLUEPILL_CONFIG`
    ;;
  stop)
    echo -n "Shutting down bluepill "
    $BLUEPILL_BIN stop
    ;;
  status)
    echo `$BLUEPILL_BIN status`
    ;;
  restart)
    ## Stop the service and regardless of whether it was
    ## running or not, start it again.
    $0 stop
    $0 start
    ;;
  *)
    ## If no parameters are given, print which are avaiable.
    echo "Usage: $0 {start|stop|status|restart}"
    exit 1
    ;;
esac